export type CodeSection = {
  id: string;
  label: string;
  tag: string;
  description: string;
  lines: [number, number];
};

export type CodeExample = {
  file: string;
  language: string;
  intro: string;
  lines: string[];
  sections: CodeSection[];
};

export const codeExamples: Record<number, CodeExample> = {
  1: {
    file: 'index.html',
    language: 'HTML',
    intro: 'HTML 负责描述页面结构。浏览器从上到下读取这些标签，再把它们画成左侧的界面。',
    lines: [
      '<!doctype html>',
      '<html lang="zh-CN">',
      '  <head>',
      '    <meta charset="UTF-8" />',
      '    <title>O/ 产品主页</title>',
      '    <link rel="stylesheet" href="style.css" />',
      '  </head>',
      '  <body>',
      '    <header class="site-header">',
      '      <a class="logo">O/</a>',
      '    </header>',
      '    <main class="hero">',
      '      <p>WELCOME TO THE WEB</p>',
      '      <h1>你的产品，值得被看见。</h1>',
      '      <p>一份 HTML，向所有人讲同一个故事。</p>',
      '      <a href="/about">ENTER →</a>',
      '    </main>',
      '  </body>',
      '</html>',
    ],
    sections: [
      { id: 'head', label: '<head>', tag: '页面信息', description: '告诉浏览器标题、编码和样式文件，通常不会直接显示在页面正文里。', lines: [3, 7] },
      { id: 'header', label: '<header>', tag: '可见页头', description: '页面上看得见的顶部区域，这里放 Logo 和导航。它和 <head> 不是一回事。', lines: [9, 11] },
      { id: 'main', label: '<main>', tag: '主要内容', description: '承载这个页面最重要、最独特的内容：标题、说明与入口。', lines: [12, 17] },
    ],
  },
  2: {
    file: 'price-configurator.js',
    language: 'JavaScript',
    intro: 'JavaScript 监听用户操作、修改状态，再把新状态写回页面。按钮因此不再只是链接。',
    lines: [
      'const plans = { basic: 99, team: 399, pro: 999 };',
      'let selectedPlan = "basic";',
      '',
      'const buttons = document.querySelectorAll("[data-plan]");',
      'const price = document.querySelector("#price");',
      '',
      'buttons.forEach((button) => {',
      '  button.addEventListener("click", () => {',
      '    selectedPlan = button.dataset.plan;',
      '    price.textContent = `¥ ${plans[selectedPlan]} / 月`;',
      '    buttons.forEach((item) => item.classList.remove("selected"));',
      '    button.classList.add("selected");',
      '  });',
      '});',
    ],
    sections: [
      { id: 'state', label: '状态', tag: '记住选择', description: 'selectedPlan 记住用户当前选中的方案。', lines: [1, 2] },
      { id: 'dom', label: '找到元素', tag: '连接界面', description: 'querySelector 把代码和页面里的按钮、价格区域连接起来。', lines: [4, 5] },
      { id: 'event', label: '事件监听', tag: '响应点击', description: 'addEventListener 在用户点击时执行更新价格和样式的代码。', lines: [7, 13] },
    ],
  },
  3: {
    file: 'request-journey.txt',
    language: 'Network trace',
    intro: '一次访问不是“浏览器直接拿到页面”，而是从地址解析开始逐层建立连接并请求资源。',
    lines: [
      'URL  https://product.example.com/guide?id=3',
      '',
      'DNS  product.example.com  →  203.0.113.42',
      '',
      'TCP  connect 203.0.113.42:443',
      'TLS  verify certificate for product.example.com',
      '',
      'HTTP GET /guide?id=3',
      '     Host: product.example.com',
      '     Accept: text/html',
      '',
      'SERVER 200 OK',
      '       Content-Type: text/html',
      '       Content-Length: 18420',
    ],
    sections: [
      { id: 'url', label: 'URL', tag: '描述目标', description: '协议、域名、路径和参数共同说明浏览器想访问什么。', lines: [1, 1] },
      { id: 'dns', label: 'DNS', tag: '寻找地址', description: '域名先被查询成网络能够路由的 IP 地址。', lines: [3, 3] },
      { id: 'http', label: 'HTTP 请求', tag: '表达需求', description: '浏览器用方法、路径和请求头告诉服务器需要哪个资源。', lines: [8, 10] },
      { id: 'server', label: '服务器响应', tag: '返回资源', description: '服务器返回状态码、内容类型和页面正文。', lines: [12, 14] },
    ],
  },
  4: {
    file: 'profile-api.ts',
    language: 'Node.js + SQL',
    intro: '动态网站先通过路由接住 API 请求，再识别用户、查询数据库并返回 JSON。',
    lines: [
      'app.get("/api/profile", async (request, response) => {',
      '  const userId = request.session.userId;',
      '',
      '  if (!userId) {',
      '    return response.status(401).json({ error: "LOGIN_REQUIRED" });',
      '  }',
      '',
      '  const user = await database.query(',
      '    "SELECT name, drafts FROM users WHERE id = ?",',
      '    [userId]',
      '  );',
      '',
      '  return response.json({ user });',
      '});',
    ],
    sections: [
      { id: 'route', label: '路由', tag: '接住请求', description: 'GET /api/profile 被分配到这段处理逻辑。', lines: [1, 1] },
      { id: 'session', label: 'Session', tag: '识别用户', description: '从会话中读取身份；没有登录就返回 401。', lines: [2, 6] },
      { id: 'database', label: '数据库', tag: '读取记忆', description: 'SQL 根据 userId 查询属于当前用户的数据。', lines: [8, 11] },
      { id: 'api', label: 'JSON 响应', tag: '交给前端', description: '后端只返回结构化数据，由前端决定怎样显示。', lines: [13, 13] },
    ],
  },
  5: {
    file: 'performance-flow.ts',
    language: 'Performance strategy',
    intro: '性能优化的核心不是“代码玄学”，而是减少距离、传输量、重复计算和低效查询。',
    lines: [
      'const asset = await cdn.get(request.url);',
      'if (asset) return asset;',
      '',
      'const cacheKey = `article:${request.params.id}`;',
      'const cached = await cache.get(cacheKey);',
      'if (cached) return response.json(cached);',
      '',
      'const article = await database.query(',
      '  "SELECT * FROM articles WHERE id = ?",',
      '  [request.params.id] // indexed column',
      ');',
      '',
      'await cache.set(cacheKey, article, { ttl: 300 });',
      'return response.json(article);',
    ],
    sections: [
      { id: 'cdn', label: 'CDN', tag: '就近返回', description: '静态资源命中边缘节点后，不必跨地域回到源站。', lines: [1, 2] },
      { id: 'cache', label: '缓存', tag: '避免重复', description: '热点数据命中缓存后，不再执行数据库查询。', lines: [4, 6] },
      { id: 'index', label: '数据库索引', tag: '快速查询', description: '索引帮助数据库直接定位目标记录。', lines: [8, 11] },
      { id: 'refresh', label: '写入缓存', tag: '准备下次', description: '数据库结果暂存一段时间，后续请求可以直接复用。', lines: [13, 14] },
    ],
  },
  6: {
    file: 'gateway.yml',
    language: 'Cloud config',
    intro: '平台化之后，很多架构能力来自配置：流量入口、服务路由、扩容规则和监控被统一管理。',
    lines: [
      'gateway:',
      '  routes:',
      '    - path: /api/users/*',
      '      service: user-service',
      '    - path: /api/content/*',
      '      service: content-service',
      '',
      'services:',
      '  content-service:',
      '    replicas: 3',
      '    autoscale: { min: 2, max: 20, cpu: 70% }',
      '    healthcheck: /health',
      '',
      'observability:',
      '  metrics: [latency, errors, traffic, saturation]',
    ],
    sections: [
      { id: 'gateway', label: '路由规则', tag: '分发流量', description: '网关根据 URL 把请求送到用户服务或内容服务。', lines: [1, 6] },
      { id: 'scale', label: '弹性伸缩', tag: '应对流量', description: 'CPU 到达阈值时自动增加实例，流量下降后再缩回。', lines: [8, 12] },
      { id: 'observe', label: '可观测性', tag: '看见系统', description: '延迟、错误、流量和饱和度共同回答“系统现在健康吗”。', lines: [14, 15] },
    ],
  },
  7: {
    file: 'content-agent.ts',
    language: 'AI application',
    intro: 'AI 原生应用把模型、知识和工具编排成一条可控链路；界面展示的是这条链路的当前状态。',
    lines: [
      'const agent = new Agent({',
      '  model: "reasoning-model",',
      '  instructions: CONTENT_STRATEGY_PROMPT,',
      '  tools: [searchKnowledge, readProject, createPlan],',
      '});',
      '',
      'const result = await agent.run(userMessage, {',
      '  context: await retrieveRelevantNotes(userMessage),',
      '  requireApproval: ["publish", "send", "delete"],',
      '});',
      '',
      'ui.render({',
      '  answer: result.output,',
      '  steps: result.toolCalls,',
      '  waitingForApproval: result.pendingAction,',
      '});',
    ],
    sections: [
      { id: 'agent', label: 'Agent 定义', tag: '能力边界', description: '模型负责推理，instructions 规定角色，tools 决定它能实际做什么。', lines: [1, 5] },
      { id: 'context', label: '知识检索', tag: '补充上下文', description: '先找到相关知识与项目资料，再把它们交给模型推理。', lines: [7, 10] },
      { id: 'approval', label: '人工确认', tag: '控制风险', description: '发布、发送和删除等有外部影响的动作必须等待用户确认。', lines: [8, 10] },
      { id: 'ui', label: '界面状态', tag: '解释过程', description: '把回答、工具步骤和待确认动作展示给用户，而不是只给一个黑盒结果。', lines: [12, 16] },
    ],
  },
};
