export type CodeSection = {
  id: string;
  label: string;
  tag: string;
  description: string;
  lines: [number, number];
};

export type CodeExample = {
  file: string;
  language: string;
  intro: string;
  lines: string[];
  sections: CodeSection[];
};

export const codeExamples: Record<number, CodeExample> = {
  1: {
    file: 'index.html',
    language: 'HTML',
    intro: 'HTML 负责描述页面结构。浏览器从上到下读取这些标签，再把它们画成左侧的界面。',
    lines: [
      '<!doctype html>',
      '<html lang="zh-CN">',
      '  <head>',
      '    <meta charset="UTF-8" />',
      '    <title>O/ 产品主页</title>',
      '    <link rel="stylesheet" href="style.css" />',
      '  </head>',
      '  <body>',
      '    <header class="site-header">',
      '      <a class="logo">O/</a>',
      '    </header>',
      '    <main class="hero">',
      '      <p>WELCOME TO THE WEB</p>',
      '      <h1>你的产品，值得被看见。</h1>',
      '      <p>一份 HTML，向所有人讲同一个故事。</p>',
      '      <a href="/about">ENTER →</a>',
      '    </main>',
      '  </body>',
      '</html>',
    ],
    sections: [
      { id: 'head', label: '<head>', tag: '页面信息', description: '告诉浏览器标题、编码和样式文件，通常不会直接显示在页面正文里。', lines: [3, 7] },
      { id: 'header', label: '<header>', tag: '可见页头', description: '页面上看得见的顶部区域，这里放 Logo 和导航。它和 <head> 不是一回事。', lines: [9, 11] },
      { id: 'main', label: '<main>', tag: '主要内容', description: '承载这个页面最重要、最独特的内容：标题、说明与入口。', lines: [12, 17] },
    ],
  },
  2: {
    file: 'price-configurator.js',
    language: 'JavaScript',
    intro: 'JavaScript 监听用户操作、修改状态，再把新状态写回页面。按钮因此不再只是链接。',
    lines: [
      'const plans = { basic: 99, team: 399, pro: 999 };',
      'let selectedPlan = "basic";',
      '',
      'const buttons = document.querySelectorAll("[data-plan]");',
      'const price = document.querySelector("#price");',
      '',
      'buttons.forEach((button) => {',
      '  button.addEventListener("click", () => {',
      '    selectedPlan = button.dataset.plan;',
      '    price.textContent = `¥ ${plans[selectedPlan]} / 月`;',
      '    buttons.forEach((item) => item.classList.remove("selected"));',
      '    button.classList.add("selected");',
      '  });',
      '});',
    ],
    sections: [
      { id: 'state', label: '状态', tag: '记住选择', description: 'selectedPlan 记住用户当前选中的方案。', lines: [1, 2] },
      { id: 'dom', label: '找到元素', tag: '连接界面', description: 'querySelector 把代码和页面里的按钮、价格区域连接起来。', lines: [4, 5] },
      { id: 'event', label: '事件监听', tag: '响应点击', description: 'addEventListener 在用户点击时执行更新价格和样式的代码。', lines: [7, 13] },
    ],
  },
  3: {
    file: 'profile-route.ts',
    language: 'Node.js + SQL',
    intro: '动态网站的页面不再是固定文件：服务器先认出用户、查询数据库，再把数据交给页面。',
    lines: [
      'app.get("/profile", async (request, response) => {',
      '  const userId = request.session.userId;',
      '',
      '  if (!userId) {',
      '    return response.redirect("/login");',
      '  }',
      '',
      '  const user = await db.query(',
      '    "SELECT name, drafts FROM users WHERE id = ?",',
      '    [userId]',
      '  );',
      '',
      '  return response.render("profile", { user });',
      '});',
    ],
    sections: [
      { id: 'route', label: '路由', tag: '接住请求', description: '用户访问 /profile 时，这段服务器逻辑开始执行。', lines: [1, 1] },
      { id: 'session', label: 'Session', tag: '识别用户', description: '从会话中读取身份；没有登录就转去登录页。', lines: [2, 6] },
      { id: 'database', label: '数据库查询', tag: '读取记忆', description: 'SQL 根据 userId 找到属于这个人的资料和草稿。', lines: [8, 11] },
      { id: 'render', label: '渲染', tag: '生成页面', description: '把查询结果注入模板，最终生成用户看到的 HTML。', lines: [13, 13] },
    ],
  },
  4: {
    file: 'Dashboard.tsx',
    language: 'React',
    intro: 'React 把界面拆成组件。状态变化时，只重新计算需要改变的那一小块界面。',
    lines: [
      'function Dashboard() {',
      '  const [view, setView] = useState("overview");',
      '  const [data, setData] = useState(null);',
      '',
      '  useEffect(() => {',
      '    fetch(`/api/dashboard?view=${view}`)',
      '      .then((result) => result.json())',
      '      .then(setData);',
      '  }, [view]);',
      '',
      '  return (',
      '    <AppShell>',
      '      <Sidebar active={view} onChange={setView} />',
      '      <DashboardContent view={view} data={data} />',
      '    </AppShell>',
      '  );',
      '}',
    ],
    sections: [
      { id: 'state', label: 'useState', tag: '页面状态', description: 'view 决定当前显示哪个视图；变化后 React 自动更新界面。', lines: [1, 3] },
      { id: 'api', label: 'fetch API', tag: '获取数据', description: '视图变化时向后端请求对应数据，不需要刷新整个页面。', lines: [5, 9] },
      { id: 'components', label: '组件', tag: '拆分界面', description: '侧栏和内容区是独立组件，各自承担清晰职责。', lines: [11, 16] },
    ],
  },
  5: {
    file: 'create-order.ts',
    language: 'TypeScript',
    intro: '交易代码关注的不只是“页面能不能点”，还要确保权限、库存和支付在异常时保持正确。',
    lines: [
      'async function createOrder(input, currentUser) {',
      '  authorize(currentUser, "order:create");',
      '',
      '  return database.transaction(async (tx) => {',
      '    const stock = await tx.stock.lock(input.sku);',
      '    if (stock.available < input.quantity) {',
      '      throw new OutOfStockError();',
      '    }',
      '',
      '    await tx.stock.decrease(input);',
      '    const payment = await pay(input.amount);',
      '    return tx.orders.save({ input, payment });',
      '  });',
      '}',
    ],
    sections: [
      { id: 'auth', label: '鉴权', tag: '确认权限', description: '在改动业务数据前，先确认当前用户是否有下单权限。', lines: [1, 2] },
      { id: 'transaction', label: '事务', tag: '保证一致', description: '库存、支付与订单被包在一个业务边界中，失败时需要回滚。', lines: [4, 13] },
      { id: 'guard', label: '业务校验', tag: '阻止错误', description: '锁定库存并检查数量，避免多人同时购买造成超卖。', lines: [5, 8] },
    ],
  },
  6: {
    file: 'gateway.yml',
    language: 'Cloud config',
    intro: '平台化之后，很多架构能力来自配置：流量入口、服务路由、扩容规则和监控被统一管理。',
    lines: [
      'gateway:',
      '  routes:',
      '    - path: /api/users/*',
      '      service: user-service',
      '    - path: /api/content/*',
      '      service: content-service',
      '',
      'services:',
      '  content-service:',
      '    replicas: 3',
      '    autoscale: { min: 2, max: 20, cpu: 70% }',
      '    healthcheck: /health',
      '',
      'observability:',
      '  metrics: [latency, errors, traffic, saturation]',
    ],
    sections: [
      { id: 'gateway', label: '路由规则', tag: '分发流量', description: '网关根据 URL 把请求送到用户服务或内容服务。', lines: [1, 6] },
      { id: 'scale', label: '弹性伸缩', tag: '应对流量', description: 'CPU 到达阈值时自动增加实例，流量下降后再缩回。', lines: [8, 12] },
      { id: 'observe', label: '可观测性', tag: '看见系统', description: '延迟、错误、流量和饱和度共同回答“系统现在健康吗”。', lines: [14, 15] },
    ],
  },
  7: {
    file: 'content-agent.ts',
    language: 'AI application',
    intro: 'AI 原生应用把模型、知识和工具编排成一条可控链路；界面展示的是这条链路的当前状态。',
    lines: [
      'const agent = new Agent({',
      '  model: "reasoning-model",',
      '  instructions: CONTENT_STRATEGY_PROMPT,',
      '  tools: [searchKnowledge, readProject, createPlan],',
      '});',
      '',
      'const result = await agent.run(userMessage, {',
      '  context: await retrieveRelevantNotes(userMessage),',
      '  requireApproval: ["publish", "send", "delete"],',
      '});',
      '',
      'ui.render({',
      '  answer: result.output,',
      '  steps: result.toolCalls,',
      '  waitingForApproval: result.pendingAction,',
      '});',
    ],
    sections: [
      { id: 'agent', label: 'Agent 定义', tag: '能力边界', description: '模型负责推理，instructions 规定角色，tools 决定它能实际做什么。', lines: [1, 5] },
      { id: 'context', label: '知识检索', tag: '补充上下文', description: '先找到相关知识与项目资料，再把它们交给模型推理。', lines: [7, 10] },
      { id: 'approval', label: '人工确认', tag: '控制风险', description: '发布、发送和删除等有外部影响的动作必须等待用户确认。', lines: [8, 10] },
      { id: 'ui', label: '界面状态', tag: '解释过程', description: '把回答、工具步骤和待确认动作展示给用户，而不是只给一个黑盒结果。', lines: [12, 16] },
    ],
  },
};
